Fix NoClassDefFoundError for DelegatingResultSet - different casting     - for prepared statement, we were casting to org.apache.tomcat.dbcp.dbcp.DelegatingPreparedStatement     - but for result sets, we were casting to org.apache.commons.dbcp.DelegatingResultSet     - not sure how this could have worked, changing to org.apache.tomcat.dbcp.dbcp.DelegatingResultSet - rename class to SQLProcessorOracleTomcatDelegate, since this is only one we have for Tomcat - use getInnermostDelegate     - was done for the prepared statement, but not the result set     - for the prepared statement, we were recursing, which getInnermostDelegate avoids - clean up and simplify the code