prolog: o Upgraded from log4j 1.2.8 to  the current 1.3alpha ( current == 10/31/2004? ) because the newer version contained a fix     for to appender reconnect code.  That is before this fix you would have case where after a connection between socketappender     and socketreceiver was lost the connection wouldn't re-establish.  e.g. start tomcat on some system, start Studio on another     connection gets established,  now shutdown studio and restart studio, connection won't re-establish. o This new log4j is incompatible with 1.2.8 in at least two ways.     a.)  The type of a non-transient field in LogEvent was changed.  ( Actually referenced class was             repackaged. )     b.) Before, LogLevel derived from Category, Category was deprecated, and Category supplied a number of          public static final objects,constants, such as DEBUG, INFO, etc.   Now even though people          would try to avoid using Category, because it was deprecated, say by using LogLevel.DEBUG the          actual refs placed in bytecode were Category.DEBUG.
          The log4j guys tried to get rid of the deprecated Category by having it derive from
           LogLevel, the opposite of what we had before, and by moving those static finals
          into LogLevel instead of having them in Category.

         If this was an attempt to maintain backward comptabiility it was futile.  As stated above
        people have refs to Category.DEBUG in their code and with this change their code breaks.
        ( At least until they recompile, and get rid of all serialized instances.. )

o The first incompatabilty doesn't matter so much so long as the only things we expect to communitcate
     through log4j are Studio and Pres Serv.  This cause we control both.

o The latter incompatiblity doesn't affect orbeon code since it doesn't use commons-logging.  Howeverw
    hile orbeon doesn't use commons-logging stuff we include, e.g. struts ( should we even include this? )
    does use commons-logging.  The latter incompatibilty would show up if you were to try and use
    the struts examples with 2.5.4 + the new log4j.

o  I originally tried to deal with above by upgrading us to commons-logging 1.0.4.  This sorta worked.
     However I found that there was a case where this would still fail, namely if commons logging
     1.0.3 was used by our servlet's  loader's parent class loader.

      So I ended up making our own build of log4j that had those public static final fields in both
      Category and Level.  This seemed to fix the pbm;





1.  Just using isolation
Get
12:35:58,795 INFO  [TomcatDeployer] deploy, ctxPath=/orbeon, warUrl=file:/C:/home2/test/jboss/a3.2.7RC1/server/default/tmp/deploy/tmp1056orbeon.war/
12:36:01,779 ERROR [BaseModelMBean] Error creating class org.apache.commons.logging.LogConfigurationException: org.apache.commons.logging.LogConfigurationException: org.apache.commons.logging.LogConfigurationException: Class org.apache.commons.logging.impl.Log4JLogger does not implement Log
12:36:01,920 ERROR [WebModule] Starting failed jboss.web.deployment:war=orbeon.war,id=-1681298618
org.jboss.deployment.DeploymentException: Error during deploy; - nested throwable: (ReflectionException: Cannot find setter method setDocBase null
Cause: java.lang.NoSuchMethodException: org.apache.commons.modeler.BaseModelMBean.setDocBase(java.lang.String))
        at org.jboss.web.AbstractWebDeployer.start(AbstractWebDeployer.java:329)
        at org.jboss.web.WebModule.startModule(WebModule.java:62)
        at org.jboss.web.WebModule.startService(WebModule.java:40)
        at org.jboss.system.ServiceMBeanSupport.jbossInternalStart(ServiceMBeanSupport.java:271)
        at org.jboss.system.ServiceMBeanSupport.jbossInternalLifecycle(ServiceMBeanSupport.java:221)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:324)
        at org.jboss.mx.server.ReflectedDispatcher.dispatch(ReflectedDispatcher.java:60)
        at org.jboss.mx.server.Invocation.dispatch(Invocation.java:62)
        at org.jboss.mx.server.Invocation.dispatch(Invocation.java:54)
        at org.jboss.mx.server.Invocation.invoke(Invocation.java:82)
        at org.jboss.mx.server.AbstractMBeanInvoker.invoke(AbstractMBeanInvoker.java:197)
        at org.jboss.mx.server.MBeanServerImpl.invoke(MBeanServerImpl.java:473)
        at org.jboss.system.ServiceController$ServiceProxy.invoke(ServiceController.java:884)
        at $Proxy18.start(Unknown Source)
...
Caused by: ReflectionException: Cannot find setter method setDocBase null
Cause: java.lang.NoSuchMethodException: org.apache.commons.modeler.BaseModelMBean.setDocBase(java.lang.String)
        at org.apache.commons.modeler.BaseModelMBean.setAttribute(BaseModelMBean.java:662)
        at org.jboss.mx.server.RawDynamicInvoker.setAttribute(RawDynamicInvoker.java:55)
        at org.jboss.mx.server.MBeanServerImpl.setAttribute(MBeanServerImpl.java:455)
        at org.jboss.web.tomcat.tc5.TomcatDeployer.performDeployInternal(TomcatDeployer.java:186)
        at org.jboss.web.tomcat.tc5.TomcatDeployer.performDeploy(TomcatDeployer.java:76)
        at org.jboss.web.AbstractWebDeployer.start(AbstractWebDeployer.java:320)
        ... 95 more
Caused by: java.lang.NoSuchMethodException: org.apache.commons.modeler.BaseModelMBean.setDocBase(java.lang.String)
        at java.lang.Class.getMethod(Class.java:978)
        at org.apache.commons.modeler.BaseModelMBean.setAttribute(BaseModelMBean.java:646)
        ... 100 more

2. If we examine the first error, the one from commons loggin before all the exceptions, we see that seems to occur because of
    1. jboss/tc creates a thread for our servlet
    2. they create a loader for us and set it as the above threads context loader
    3. they use commons-logging
     4. commons-logging, loaded by jboss/tc loader, in turn uses our context loader to load logging support
     5.  our loader ignores parent loaders loaded classes and instead loads logging support classes for it
           self.
     6. jboss/tc loaded commons logging throws because the classes it got from step 4/5 are not assignable
         to the types it has.  ( Cause different loaders )
     7. jboss/tc doesn't handle above correctly and instead leads to red herring, error msg about setDocBase

3.  If we remove commons-logging and log4j from orbeon war then we get
dan5: org.jboss.mx.loading.UnifiedClassLoader3@b5615d{ url=file:/C:/home2/test/jboss/a3.2.7RC1/server/default/tmp/deploy/tmp43306orbeon.war/ ,addedOrder=34}
13:46:56,764 ERROR [LoggerFactory] Cannot load Log4J configuration. Skipping logging initialization
java.lang.LinkageError: loader constraints violated when linking org/w3c/dom/Element class
        at org.orbeon.oxf.util.LoggerFactory.initLogger(LoggerFactory.java:73)
        at org.orbeon.oxf.webapp.WebAppContext.<init>(WebAppContext.java:90)
        at org.orbeon.oxf.webapp.WebAppContext.instance(WebAppContext.java:61)
        at org.orbeon.oxf.servlet.OXFServletDelegate.init(OXFServletDelegate.java:54)
        at javax.servlet.GenericServlet.init(GenericServlet.java:211)

This happens because the DOMConfgurator we use was loaded by the log4j loader while the org.w3c.dom classes were loaded
by our loader ( which is getting the dom classes from xerces api jar )

The servlet does load btw, only logging is affected.

4. If put the logj4 jar back in the war then we get
log4j-internal: 860 config.PropertySetter  - Set child component of type [org.apache.log4j.PatternLayout] for [org.apache.log4j.ConsoleAppender].
log4j:ERROR Could not create an Appender. Reported error follows.
java.lang.ClassCastException
        at org.apache.log4j.xml.DOMConfigurator.parseAppender(Unknown Source)
        at org.apache.log4j.xml.DOMConfigurator.findAppenderByName(Unknown Source)
        at org.apache.log4j.xml.DOMConfigurator.findAppenderByReference(Unknown Source)
        at org.apache.log4j.xml.DOMConfigurator.parseChildrenOfLoggerElement(Unknown Source)
        at org.apache.log4j.xml.DOMConfigurator.parseRoot(Unknown Source)
        at org.apache.log4j.xml.DOMConfigurator.parse(Unknown Source)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(Unknown Source)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(Unknown Source)

followed by

log4j:ERROR Could not parse input source [org.xml.sax.InputSource@572090].
java.lang.NullPointerException
        at java.util.Hashtable.put(Hashtable.java:393)
        at org.apache.log4j.xml.DOMConfigurator.findAppenderByName(Unknown Source)
        at org.apache.log4j.xml.DOMConfigurator.findAppenderByReference(Unknown Source)
        at org.apache.log4j.xml.DOMConfigurator.parseChildrenOfLoggerElement(Unknown Source)
        at org.apache.log4j.xml.DOMConfigurator.parseRoot(Unknown Source)
        at org.apache.log4j.xml.DOMConfigurator.parse(Unknown Source)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(Unknown Source)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(Unknown Source)
        at org.apache.log4j.xml.DOMConfigurator.doConfigure(Unknown Source)
        at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:521)
        at org.apache.log4j.helpers.IntializationUtil.initialConfiguration(IntializationUtil.java:86)
        at org.apache.log4j.LogManager.<clinit>(LogManager.java:107)
        at org.apache.log4j.Logger.getLogger(Logger.java:60)
        at org.orbeon.oxf.util.LoggerFactory.createLogger(LoggerFactory.java:37)
        at org.orbeon.oxf.util.LoggerFactory.<clinit>(LoggerFactory.java:34)
        at org.orbeon.oxf.webapp.WebAppContext.<clinit>(WebAppContext.java:44)

It seems that jboss is setting some sys prop that tells log4j to first load some jboss log4j.xml.
It also seems that jboss unsets this property after we're loaded.  Say this cause
the  java integ sample ( which dumps sys props ) does show any log4j props.

5.  If I set
         	System.setProperty( "log4j.configuration", "-there-aint-no-such-file-" );
     in our logger factory the above exceptions go away.

6.  If we put commons logging jar in web-inf/lib/private-lib and then add classpath entry in
      orbeon.jar's manifest then we can deliver commons-logging without having it clash
      with jboss.  This because of the funky order jboss implements when class path entries are
       used _and_ one specifies 'load my stuff first'.   The order is
       web-inf/classes, web-inf/lib, jboss repository( parent ), class path manfiest entries.